import { precacheAndRoute } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { NetworkFirst, StaleWhileRevalidate } from "workbox-strategies";
import { ExpirationPlugin } from "workbox-expiration";
import { CacheableResponsePlugin } from "workbox-cacheable-response";

declare const self: any;

// Precache resources generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// 1. Caching of API calls
registerRoute(
  /^https:\/\/appwrite\.agenc-ia\.net\/v1\/.*/,
  new NetworkFirst({
    cacheName: "api-cache",
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 * 7, // 1 week
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  }),
);

// 2. Navigation routing - fallback to index.html/offline support
registerRoute(
  ({ request }) => request.mode === "navigate",
  new NetworkFirst({
    cacheName: "pages-cache",
    networkTimeoutSeconds: 3,
  }),
);

// 3. Static assets caching (images, fonts, scripts, styles)
registerRoute(
  /\.(?:js|css|png|jpg|jpeg|svg|gif|ico|woff2)$/,
  new StaleWhileRevalidate({
    cacheName: "static-assets",
    plugins: [
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  }),
);

// Escutar eventos de Push
self.addEventListener("push", (event: any) => {
  if (!event.data) return;

  try {
    const payload = event.data.json();
    const title = payload.title || "AutoPeças ERP";
    const options: NotificationOptions = {
      body: payload.body || "",
      icon: payload.icon || "/pwa-icon-192.png",
      badge: payload.badge || "/favicon.ico",
      data: payload.data || {},
    };

    event.waitUntil(self.registration.showNotification(title, options));
  } catch (err) {
    console.error("Erro ao processar notificação push recebida:", err);
  }
});

// Escutar clique na notificação
self.addEventListener("notificationclick", (event: any) => {
  event.notification.close();
  const urlToOpen = event.notification.data?.url || "/";

  event.waitUntil(
    self.clients
      .matchAll({ type: "window", includeUncontrolled: true })
      .then((windowClients: any[]) => {
        // Se houver uma aba aberta com o ERP, foca nela
        for (const client of windowClients) {
          if (client.url.includes(urlToOpen) && "focus" in client) {
            return client.focus();
          }
        }
        // Caso contrário, abre uma nova janela
        if (self.clients.openWindow) {
          return self.clients.openWindow(urlToOpen);
        }
      }),
  );
});
export {};
